### ISSUE TITLE
There are no functions like: video = load_batch(batch_idx)  and     train_on_video(video)  in repo: Give the example to run this repo with original function

### ISSUE THREAD

**Issue by adeebakausar** [okankop/vidaug#4] opened 2019-05-13 10:32 UTC
for batch_idx in range(1000):
    # 'video' should be either a list of images from type of numpy array or PIL images
    video = load_batch(batch_idx)
    video_aug = seq.augment_images(video)
    train_on_video(video)

**Comment by ahmetgunduz** [comment] 2019-05-14 21:48
Duplicate of #6

**Closed** 2019-05-15 10:32 UTC
