### ISSUE TITLE
How to input the videos

### ISSUE THREAD

**Issue by MritulaC** [okankop/vidaug#3] opened 2019-04-23 13:08 UTC
Hi,
 Thanks for the code. Just wanted to know how to pass multiple images to the code for Video Augmentation.

Thanks,
 Mritula

**Comment by ahmetgunduz** [comment] 2019-05-14 21:51
Please check the examples folder. I have committed an example for it where I got the inputs from one of the gifs. But in practice, it is the same procedure regardless of input as long as you read the video frames from any tipe of fike (video (mp4, gif, mov ) i.e.  stack of frames).

**Comment by okankop** [comment] 2019-06-13 11:29
I believe the issue is resolved! You can reopen the issue if necessary!

**Closed by okankop** 2019-06-13 11:29 UTC
